### ISSUE TITLE
Upgrade all applications that use django-ucamlookup to 1.9.5

### ISSUE THREAD

**Issue by abrahammartin** [abrahammartin/django-ucamlookup#3]

**Comment by rjg21** [comment]
django-ucamlookup is referenced in the following repos:
- [x] django-automationcommon [1]
- [x] dockerimages
- [x] iar-migrate (unused)
- [x] lookupproxy
- [x] mws-panel
- [x] pidash-webapp
- [x] ssgw-lookup-api (unused)
- [x] ssgw-webapp
- [x] tlscerts
- [x] raven metadata

[1] which is additionally referenced to by:
- [x] django-boilerplate (not a service)
- [ ] gauth-webapp
- [x] hydra-consent-app
- [x] iar-backend
- [x] iar-gatherstats

**Tick when service known to be running 1.9.5**

**Comment by msb** [comment]
I have checked and neither hydra-consent-app or hydra-consent-app actually use django-ucamlookup directly

**Comment by abrahammartin** [comment]
pidash now done

**Comment by abrahammartin** [comment]
@ph448 confirmed the other day that mws-panel was also done so ticking that as well

**Comment by abrahammartin** [comment]
metadata done, now only waiting for tlscerts

**Comment by abrahammartin** [comment]
and all done
